### PR TITLE
Allow config dir to be overridden.

### PR DESCRIPTION
**Pull request by bitdancer**
Thanks for writing and publishing the script, it is very handy.  Here is
a small improvement I found useful.

### CODE REVIEW

**Comment by 0x17de** [comment]
Hey @bitdancer , thanks for the changes. I have put a comment on the commit. Maybe it could be made even more flexible. What do you think?

**Comment by bitdancer** [comment]
Well, I implemented what I wanted: all my docker-compose files are in subdirectories off of /var/lib/local, so I wanted that to be a global change, not one I had to put in the `.conf` file for every one of my services.

*Also* making the full path configurable is a good idea, though.  That's easy to do, we just need make the assignment to SUBCFG also be conditional.  I'll add that.

**Comment by bitdancer** [comment]
Done.  I tested it locally, both with and without an alternate path set.

**Comment by 0x17de** [comment]
thank you very much :) looks great

**Pull request merged**
